arm: mmp: Fix build issue due to PXA NAND pdata structure changes
A previous work removed a few useless fields in PXA NAND platform data.
Changes have been reflected in all impacted files but the ones in the
mach-mpp directory. Update these file to fix build issues like:

    arch/arm/mach-mmp/aspenite.c:175:3:
    error: 'struct pxa3xx_nand_platform_data' has no member
    named 'enable_arbiter'

Fixes: 6e836cc71870 ("mtd: nand: remove useless fields from pxa3xx NAND platform data")
Signed-off-by: Miquel Raynal <miquel.raynal@bootlin.com>